name: Deploy Static Site
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH to Kali Linux
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            # Ensure working as correct user (check for sudo availability)
            if command -v sudo > /dev/null; then
              SUDO="sudo"
            else
              SUDO=""
            fi

            # Create or clean the deployment directory
            $SUDO rm -rf /var/www/static-site
            $SUDO mkdir -p /var/www/static-site
            $SUDO chown -R $USER:$USER /var/www/static-site

            # Clone the repo into the deployment directory
            git clone https://github.com/VathanakSol/basic-html.git /var/www/static-site

            # Restart nginx if installed
            if $SUDO systemctl is-active nginx > /dev/null; then
              $SUDO systemctl restart nginx
            else
              echo "Nginx is not active or not installed."
            fi
